name: ai_resume_builder

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}  # Set API key to environment variable

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |                                  
        python -m pip install --upgrade pip  
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set PYTHONPATH                          # Allows Python to find src module
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV  # Set the PYTHONPATH to src folder
                                                    # $GITHUB_ENV stores env variables
    - name: Run ai_resume_builder
      run: |
        python src/ai_resume_builder/resume_generator.py  # Run ai_resume_builder module

  run_pylint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |                                  
        python -m pip install --upgrade pip  
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi    

    - name: Set PYTHONPATH                          # Allows Python to find src module
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV  # Set the PYTHONPATH to src folder
                                                    # $GITHUB_ENV stores env variables

    - name: Run pylint on ai_resume_builder
      run: |
        echo "Current Directory: $(pwd)"
        echo "PYTHONPATH: $PYTHONPATH"
        pylint src/ai_resume_builder  # Run pylint on ai_resume_builder directory

  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |                                  
        python -m pip install --upgrade pip  
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set PYTHONPATH                          # Allows Python to find src module
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV  # Set the PYTHONPATH to src folder
                                                    # $GITHUB_ENV stores env variables
    - name: Run tests
      run: |      
        echo "Current Directory: $(pwd)"
        echo "PYTHONPATH: $PYTHONPATH"
      env:
        API_KEY: ${{ secrets.API_KEY }}  # Set API key to environment variable for tests