name: keeping_api_key_secret

on:
  push:
    branches:
      - "*"

jobs:
  check-protected-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for modifications in api_key.txt
        run: |
          if git diff --name-only HEAD^ HEAD | grep "src/ai_resume_builder_source_text_files_api_key.txt"; then
            echo "ERROR: Changes to api_key.txt are not allowed."
            exit 1
          fi