name: job_search_database

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}  # Set API key to environment variable

    steps:
    - name: Checkout code
      uses: actions/checkout@v2   # use GitHub checkout action to clone the repository to the runner

    - name: Set up Python
      uses: actions/setup-python@v2  # Installs Python on the runner
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |                                  # Upgrades pip and installs dependencies
        python -m pip install --upgrade pip  
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set PYTHONPATH                          # Allows Python to find src module
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV  # Set the PYTHONPATH to src folder
                                                    # $GITHUB_ENV stores env variables
    - name: Run job_search_database
      run: python src/job_search_database/job_search_database_driver.py  # Run job_search_database module

  run_pylint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2   # use GitHub checkout action to clone the repository to the runner

    - name: Set up Python
      uses: actions/setup-python@v2  # Installs Python on the runner
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |                                  # Upgrades pip and installs dependencies
        python -m pip install --upgrade pip  
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi    

    - name: Set PYTHONPATH                          # Allows Python to find src module
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV  # Set the PYTHONPATH to src folder
                                                    # $GITHUB_ENV stores env variables
    - name: Run pylint on job_search_database
      run: |
        echo "Current Directory: $(pwd)"
        echo "PYTHONPATH: $PYTHONPATH"
        pylint src/job_search_database  # Run pylint on job_search_database directory
      continue-on-error: true

    - name: Run pylint on tests
      run: |
        export PYTHONPATH=$(pwd)
        pylint tests/test_job_search_database  # Run pylint on tests directory

  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2   # use GitHub checkout action to clone the repository to the runner

    - name: Set up Python
      uses: actions/setup-python@v2  # Installs Python on the runner
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |                                  # Upgrades pip and installs dependencies
        python -m pip install --upgrade pip  
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set PYTHONPATH                          # Allows Python to find src module
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV  # Set the PYTHONPATH to src folder
                                                    # $GITHUB_ENV stores env variables
    - name: Run tests
      run: |      
        echo "Current Directory: $(pwd)"
        echo "PYTHONPATH: $PYTHONPATH"
        pytest tests/test_job_search_database  # Run the tests specific to job_search_database
      env:
        API_KEY: ${{ secrets.API_KEY }}  # Set API key to environment variable for tests
