name: job_search_gui

on:
  push:
    branches:
      - main

jobs:
  build-and-run-gui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set PYTHONPATH                          # Allows Python to find src module
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV  # Set the PYTHONPATH to src folder
                                                      # $GITHUB_ENV stores env variables

        # Provides a virtual display to fun GUI apps in headless env
      - name: Install xvfb
        run: sudo apt-get install -y xvfb

        # Launch a virtual X server, which allows Tkinter to function
      - name: Run job_search_gui script with xvfb
        run: |
          python src/job_search_database/job_search_database_driver.py  # Run job_search_database module
          timeout 30 xvfb-run --auto-servernum python src/job_search_gui/job_search_gui_driver.py

  run_pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi    

      - name: Set PYTHONPATH                          # Allows Python to find src module
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV  # Set the PYTHONPATH to src folder
        # $GITHUB_ENV stores env variables

      - name: Run pylint on job_search_gui
        run: |
          echo "Current Directory: $(pwd)"
          echo "PYTHONPATH: $PYTHONPATH"
          pylint src/job_search_gui  # Run pylint on ai_resume_builder directory

  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set PYTHONPATH                          # Allows Python to find src module
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV  # Set the PYTHONPATH to src folder
        # $GITHUB_ENV stores env variables
      - name: Run tests
        run: |
          echo "Current Directory: $(pwd)"
          echo "PYTHONPATH: $PYTHONPATH"